# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS — LightDM greeting into a Cinnamon session.
---
displaymanagers:
    - lightdm

basicSetup:     false
sysconfigSetup: false

defaultDesktopEnvironment:
    executable: "cinnamon"
    desktopFile: "cinnamon"

lightdm:
    preferred_greeters: [ "slick-greeter.desktop", "lightdm-gtk-greeter.desktop" ]
