# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS — /etc/default/grub tuning.
---
overwrite:        false
prefer_grub_d:    false
keep_distributor: false
kernel_params:    [ "quiet", "splash" ]
defaults:
    GRUB_TIMEOUT:            5
    GRUB_DEFAULT:            "saved"
    GRUB_DISABLE_SUBMENU:    true
    GRUB_TERMINAL_OUTPUT:    "console"
    GRUB_DISABLE_RECOVERY:   true
    GRUB_DISTRIBUTOR:        "Yaya OS"
always_use_defaults: false
