# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS keyboard — interactive, defaults to US (QWERTY).
# The user may change layout/variant/model on the keyboard page.
---
xOrgConfFileName:      "/etc/X11/xorg.conf.d/00-keyboard.conf"
convertedKeymapPath:   "/lib/kbd/keymaps/xkb"
writeEtcDefaultKeyboard: true

# Defaults shown pre-selected on the page.
keyboardModel:   "pc105"
keyboardLayout:  "us"
keyboardVariant: ""
