# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS — fresh machine-id on the installed system.
---
systemd:       true
systemd-style: uuid
dbus:          true
dbus-symlink:  true
entropy-copy:  false
