# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS — post-install package cleanup on the target (apt backend).
# Strips the installer and live-only machinery from the installed system.
---
backend: apt
skip_if_no_internet: false
update_db: false
update_system: false

operations:
  - try_remove:
    - calamares
    - live-boot
    - live-boot-initramfs-tools
    - live-config
    - live-config-systemd
