# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS partitioning. ext4 by default; optional LUKS encryption offered
# in the "Erase disk" flow (the old preseed always forced crypto — here it
# is the user's choice).
---
efi:
    mountPoint:      "/boot/efi"
    recommendedSize: 300MiB
    minimumSize:     32MiB
    label:           "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

luksGeneration:            luks2
drawNestedPartitions:      false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice:         small
defaultFileSystemType:     "ext4"
availableFileSystemTypes:  [ "ext4", "btrfs", "xfs" ]

# Offer the encryption checkbox in guided partitioning.
enableLuksAutomatedPartitioning: true

essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
    enable: true
