# SPDX-License-Identifier: GPL-3.0-or-later
# Remove the live-session user from the installed system.
# The live user is "live" (set via bootappend username=live) so it can
# never collide with whatever account the installer creates.
---
username: live
