# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS — enable the core services on the installed system.
# (The display manager is handled by the displaymanager module.)
---
units:
    - name: "NetworkManager.service"
      action: "enable"
      mandatory: false
    - name: "bluetooth.service"
      action: "enable"
      mandatory: false
