# SPDX-License-Identifier: GPL-3.0-or-later
# Yaya OS — copy the live SquashFS onto the target.
# Debian live-build places the image at /run/live/medium/live/filesystem.squashfs.
---
unpack:
    - source:      "/run/live/medium/live/filesystem.squashfs"
      sourcefs:    "squashfs"
      destination: ""
